### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by a0972210123** [google-developer-training/android-basics-kotlin-unscramble-app#85]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**

Late-initialize currentScrambledWord

after adding the code change below:

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by CalShark21** [comment]
I'm having the same problem. Theres a NullPointerException somewhere in the getNextWord() function and I can't figure it out.

**Comment by swastiksharma1999** [comment]
Same Here

**Comment by CalShark21** [comment]
Meant to add this last night but I figured it out: 

The `init {...}` block needs to be **after** all of the class variables. That solved it for me (tutorial wasn't clear on this, especially since it tells you about the init block before the variables). Hope that helps!

**Comment by swastiksharma1999** [comment]
In My case, I changed this:

`private lateinit var _currentScrambledWord = "test"`
`val currentScrambledWord: String=_currentScrambledWord`

To

`private var _currentScrambledWord = "test"`
`val currentScrambledWord: String`
 `get() = _currentScrambledWord`

And It worked!
It would be helpful if someone could explain the difference between these 2 implementations to me

**Comment by CalShark21** [comment]
So I'm not sure what the original error you having was (was it a NullPointerException?) but it looks like there might be some wonky stuff going on in those implementations. With the first one: 

`private lateinit var _currentScrambledWord = "test"
val currentScrambledWord: String=_currentScrambledWord`

We changed `_currentScrambledWord` to a lateinit in order to initialize what it will be at runtime (so it won't display "test" as the first word), but in that case you should get rid of the `... = "test` and replace it with a explicit data-type: `private lateinit var _currentScrambledWord: String`

And then you shouldn't have `val currentScrambledWord: String=_currentScrambledWord` at all as we're using a backing property for that variable (as in the second implementation you have there). So finally you should be left with this for those variables:

`   private lateinit var _currentScrambledWord: String
    val currentScrambledWord: String 
        get() = _currentScrambledWord`

And of course your init { } block after should include the call to `getNextWord()`:

`init {
    Log.d("GameFragment", "GameViewModel created!")
    getNextWord()
}`

I hope that helps explain it a little! I'd be curious to see if that implementation works for you or if you're still getting a bug, let me know!
